name: bid
description: easy bid
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <=3.16.2"
dependencies:
  flutter:
    sdk: flutter
  # firebase services
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  cloud_functions: ^4.3.2
  firebase_storage: ^11.2.2
  # Cupertino Icons and font
  cupertino_icons: ^1.0.3
  # state
  provider: ^6.0.1
  # save file
  path_provider: ^2.0.6
  # format dates
  intl: ^0.17.0
  # take image
  image_picker: ^0.8.5+3
  # check permission
  permission_handler: ^8.2.6
  # hive for local database
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  # alert
  cool_alert: ^1.1.0
  # url_launcher
  url_launcher: ^6.1.5
  # fonts
  google_fonts: ^4.0.0
  # lottie animation
  lottie: ^1.4.3
  # splash screen
  flutter_native_splash: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^1.1.1
  build_runner: ^2.1.5

flutter_native_splash:
  color: "#ffffff"
  image:  assets/images/splash.png
  android: true
  ios: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/VarelaRound-Regular.ttf
    - assets/fonts/ArialUnicodeMS.ttf
    - assets/fonts/OpenSans-Bold.ttf
    - assets/fonts/OpenSans-Regular.ttf
    - assets/images/login_wallpaper.jpeg
    - assets/animations/empty.json
    - assets/animations/loading.json
    - assets/animations/data_not_found.json
    - assets/animations/error.json
    - assets/animations/small_error.json
    - assets/images/

